import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopMenu from '@/components/TopMenu'
import { authOptions } from './api/auth/[...nextauth]/route'
import NextAuthProvider from '@/providers/NextAuthProvider'
import { getServerSession } from 'next-auth'
import { Suspense } from 'react'
import CircularProgress from '@mui/joy/CircularProgress';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import './globals.css'
import getUserProfile from '@/libs/getUserProfile'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)
  console.log('wow')
  console.log(session)
  const profile = getUserProfile(session)

  return (
    <html lang="en">
      <body className={inter.className}>
        
          <NextAuthProvider session={session}>
            {
              session ? <TopMenu id={session.user.name.toUpperCase()}/> : null
            }
            {children}
          </NextAuthProvider>
      </body>
    </html>
  )
}
